import type { Car } from '@/types';

export const cars: Car[] = [
  {
    id: '1',
    make: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    price: 89990,
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Midnight Silver',
    rating: 4.9,
    reviews: 342,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80',
    badge: 'New Arrival',
    features: ['Autopilot', 'Ludicrous Mode', '1020 HP', 'Over-the-air updates', '21" Arachnid Wheels'],
    description: 'The Tesla Model S Plaid redefines what a performance sedan can be. With tri-motor all-wheel drive and the most advanced battery technology, it delivers supercar performance in everyday luxury.',
    acceleration: '1.99s 0-60mph',
    topSpeed: '200 mph',
    range: '396 miles',
    horsepower: 1020,
  },
  {
    id: '2',
    make: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    price: 74900,
    mileage: 1200,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Coupe',
    color: 'Isle of Man Green',
    rating: 4.8,
    reviews: 218,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    badge: 'Hot Deal',
    features: ['M Carbon Roof', 'Adaptive M Suspension', 'Carbon Ceramic Brakes', 'M Drivers Package', 'Harman Kardon Audio'],
    description: 'The BMW M4 Competition is the pinnacle of driving pleasure, combining raw performance with everyday usability. Its twin-turbocharged inline-six produces thunderous power.',
    acceleration: '3.8s 0-60mph',
    topSpeed: '180 mph',
    horsepower: 503,
  },
  {
    id: '3',
    make: 'Porsche',
    model: 'Taycan Turbo S',
    year: 2024,
    price: 185000,
    mileage: 500,
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Frozen Blue Metallic',
    rating: 4.9,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    badge: 'Premium',
    features: ['Launch Control', 'PDCC Sport', 'Ceramic Composite Brakes', '21" RS Spyder Design Wheels', 'Burmester Sound'],
    description: 'The Porsche Taycan Turbo S represents the future of performance. It combines Porsche DNA with all-electric efficiency, delivering a driving experience like no other EV.',
    acceleration: '2.6s 0-60mph',
    topSpeed: '162 mph',
    range: '280 miles',
    horsepower: 750,
  },
  {
    id: '4',
    make: 'Mercedes',
    model: 'G 63 AMG',
    year: 2023,
    price: 164500,
    mileage: 8900,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Designo Obsidian Black',
    rating: 4.7,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',
    features: ['AMG SPEEDSHIFT TCT 9G', 'AMG Ride Control+', 'Night Package', 'Burmester Surround Sound', 'Active Multicontour Seats'],
    description: 'An icon reimagined. The Mercedes-AMG G 63 combines legendary off-road capability with AMG performance and handcrafted luxury for an unmatched presence.',
    acceleration: '4.5s 0-60mph',
    topSpeed: '137 mph',
    horsepower: 577,
  },
  {
    id: '5',
    make: 'Lamborghini',
    model: 'Urus S',
    year: 2024,
    price: 232000,
    mileage: 200,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Arancio Borealis',
    rating: 4.8,
    reviews: 94,
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
    badge: 'Exotic',
    features: ['ANIMA Selector', 'Torque Vectoring', 'Carbon Ceramic Brakes', 'Bang & Olufsen Sound', 'Night Vision Assist'],
    description: "The Lamborghini Urus S is the world's first Super Sport Utility Vehicle. It embodies the Lamborghini DNA in a versatile form, delivering unprecedented performance.",
    acceleration: '3.5s 0-60mph',
    topSpeed: '190 mph',
    horsepower: 666,
  },
  {
    id: '6',
    make: 'Audi',
    model: 'RS e-tron GT',
    year: 2024,
    price: 139900,
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Kemora Gray',
    rating: 4.7,
    reviews: 127,
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80',
    badge: 'New Arrival',
    features: ['Matrix LED Headlights', 'Dynamic All-wheel Steering', 'Carbon Fiber Interior', 'Bang & Olufsen 3D Sound', '21" Turbine Design Wheels'],
    description: 'The Audi RS e-tron GT is a masterpiece of engineering and design. With stunning looks and blistering performance, it sets a new standard for electric grand tourers.',
    acceleration: '3.1s 0-60mph',
    topSpeed: '155 mph',
    range: '232 miles',
    horsepower: 637,
  },
  {
    id: '7',
    make: 'Ferrari',
    model: 'SF90 Stradale',
    year: 2024,
    price: 507000,
    mileage: 0,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'Coupe',
    color: 'Rosso Corsa',
    rating: 5.0,
    reviews: 43,
    image: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80',
    badge: 'Exotic',
    features: ['PHEV Powertrain', 'eManettino', 'RAC-e (Radar Cruise Control)', 'Carbon Fibre Body', 'Ferrari Dynamic Enhancer+'],
    description: 'The Ferrari SF90 Stradale is the most powerful Ferrari ever built for road use. Its plug-in hybrid powertrain represents the future of the prancing horse.',
    acceleration: '2.5s 0-60mph',
    topSpeed: '211 mph',
    range: '16 miles EV',
    horsepower: 986,
  },
  {
    id: '8',
    make: 'Range Rover',
    model: 'Sport SV',
    year: 2024,
    price: 169500,
    mileage: 3400,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Charente Grey',
    rating: 4.6,
    reviews: 201,
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    features: ['SV Bespoke', 'Active Rear Locking Differential', 'Carbon Ceramic Brakes', 'Meridian Signature Sound', 'Deployable Side Steps'],
    description: 'The Range Rover Sport SV combines the capability of a Range Rover with the performance of a supercar, wrapped in the most luxurious sport utility vehicle ever made.',
    acceleration: '3.6s 0-60mph',
    topSpeed: '180 mph',
    horsepower: 626,
  },
];

export const makes = ['All', 'Tesla', 'BMW', 'Porsche', 'Mercedes', 'Lamborghini', 'Audi', 'Ferrari', 'Range Rover'];
export const bodyTypes = ['All', 'Sedan', 'SUV', 'Hatchback', 'Coupe', 'Truck', 'Van'];
export const fuelTypes = ['All', 'Electric', 'Petrol', 'Diesel', 'Hybrid'];
export const transmissions = ['All', 'Automatic', 'Manual'];
